name: master-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn build

      - name: Build and push docker
        run: |
          docker build -t crustio/crust-apps:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push crustio/crust-apps:latest

      - name: Upgrade apps
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull crustio/crust-apps:latest
            cd /opt/compose
            docker-compose up -d crust-apps
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}